### PR TITLE
 feat(svelte-store): Svelte adapter

### PR DESCRIPTION
**Pull request by david-roeger**
This PR:

- [x] Adds initial implementation of the Svelte adapter
- [x]  Adds initial tests for the Solid adapter

Regarding the questions in the issue:

1. Packaging - I switched from tsub to [svelte-package](https://kit.svelte.dev/docs/packaging) the official svelte way of well building packages. The build output from tsub threw errors when I tried to use it.
2. Testing - I used  [testing-library](https://testing-library.com/docs/svelte-testing-library/intro/) svelte version. (The test for counting the rerender is a bit ugly because of https://github.com/testing-library/svelte-testing-library/issues/222)
3. Reactivity interop - since svelte offers native store support this is quite nice. For the Api surface I tried to stay as close to the other packages.

Note: I just copy and pasted the shallow function - it might be worth refactoring that into the core package?

Closes https://github.com/TanStack/store/issues/4

### CODE REVIEW

**Comment by david-roeger** [comment]
For the setup of the whole package I mainly copied and pasted from the vue example and [svelte-query](https://github.com/TanStack/query/tree/main/packages/svelte-query). I hope the setup is fine.

**Comment by crutchcorn** [comment]
This looks great to me, but I'm not a Svelte-spert admittedly 😅

Tagging in @LukeHagar to review the Svelte code, as he was offering to help out with a Svelte adapter for Forms

**Comment by LukeHagar** [comment]
I just wanted to follow up here, this looks like a good implementation, and I'm glad to see you using the existing Svelte store functions.

That being said I think this will end up changing once runes come about.

**Review by LukeHagar — APPROVED** [review]

**Comment by crutchcorn** [comment]
Let's hold off for Svelte 5

**Comment by david-roeger** [comment]
Hey there,
with Svelte 5 now being in Release Candidate Stage I would be like to continue working on the adapter :)

**Comment by LukeHagar** [comment]
Sounds great to me!

**Comment by crutchcorn** [comment]
Hey all! Sorry I missed this. Asking some folks to review now via socials. I'm not super familiar with Svelte 5 yet. Let me also tag in @lachlancollins to see if we can fix up Knip and Nx in this PR

**Comment by wobsoriano** [comment]
@crutchcorn Not a Svelte pro, but I've been experimenting with runes (trying to convert the [svelte-sonner](svelte-sonner.vercel.app) package to runes), and I can say the implementation looks good here. The only suggestion I have is the possibility of exporting the`shallow` function from the vanilla package so that it can be imported by the Vue, React, and Svelte packages.

**Review by lachlancollins — APPROVED** [review]
Hi @david-roeger , I've made structural changes to the adapter to better match how we do it in other TanStack projects (e.g. https://github.com/TanStack/query/tree/main/packages/svelte-query) - this removes the dependency on `@sveltejs/kit` (no more `svelte-kit sync`).

@crutchcorn I've fixed the Knip issues, but there does seem to be a Vitest coverage issue with the v5 RC, I'm sure it'll be fixed sometime soon.

**Review by crutchcorn — APPROVED** [review]
This is awesome, thank you **so much** for your help here!

**Pull request merged**
